---
name: Create changelog
on: 
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: bdashrad/git-chlog-action@v2.0.0
        with:
          next_version: "0.11.0"
